### ISSUE TITLE
Update website and email on copyright page

### ISSUE THREAD

**Issue by christopheradams** [waiting4bassel/waiting-gitbook#2]
http://waiting4bassel.cc/
info@waiting4bassel.cc

**Comment by danatrometer** [comment]
?

**Comment by danatrometer** [comment]
Ok got it ;) like all other web notifications I get from my hubby all day on our servers etc 
Weird xxxxxx
I want to meet u man

**Comment by christopheradams** [comment]
:)

**Comment by rejon** [comment]
Hahahah
